version: '3.8'
services:
    frontend:
        container_name: habits_frontend
        image: habits_frontend:dev
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        # working_dir: /app/frontend
        volumes:
            - ./frontend:/usr/app
            # - /app/node_modules
        environment:
            TZ: 'Asia/Seoul'
        networks:
            - my_network
    backend:
        container_name: habits_backend
        image: habits_backend:dev
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        # working_dir: /app/backend
        volumes:
            - './backend:/app'
            - '/app/node_modules'
        environment:
            TZ: 'Asia/Seoul'
        networks:
            - my_network
        depends_on:
            - mysqldb
    mysqldb:
        image: habits_mysql:dev
        container_name: mysqldb
        restart: always
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3307:3306
        # environment:
        #     MYSQL_ROOT_PASSWORD: '!docker'
        #     MYSQL_DATABASE_NAME: HABITS
        # env_file:
        #     - ./db/.env
        networks:
            - my_network

volumes:
    mysql-data:

networks:
    my_network:
        driver: bridge
